### ISSUE TITLE
Merge `dpservice-go` and `dpservice-cli` into `dpservice` project and simplify testing setup

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/dpservice#445]
# Why?

Currently we are generating the Golang bindings from the `dpservice` proto file in a seperate project (`dpservice-go`). This `dpservice-go` project is then used inside `dpservice-cli` to create a CLI for interacting with the `dpservice`. Each project has it's own GH lifecycle and release code in place. 

This causes some very bad side-effects when running end to end tests:
- Getting the latest (matching CLI) has to be done in the `dpservice` project via an own set of scripts
- This process is very error prune and might break as we have to keep all 3 projects in sync
- We have to do the housekeeping 3x across all projects
- We have to maintain Github actions across all 3 projects

## Proposed solution

Move `dpservice-go` into a folder called `go` inside the `dpservice` project. This place will hold the generated golang protobuf files.

Move `dp-service-cli` into a folder called `cli`. This will be the home of the CLI packages. The goreleaser job will release the CLI packages as part of the `dpservice` release. That way we ensure the compatibility of the CLI with the underlying `dpservice` code base.

As a side note: the prometheus exported can be also be placed inside the `dpservice` project as it is tightly coupled with the `dpservice`. That way we can ensure functional integrity of the exported code.

**Comment by afritzler** [comment]
The point is, there should be no need to download any artefacts. Instead you should install in the `Makefile` all necessary tools into a gitinored `bin` folder to run all your tests. You can find an example here: https://github.com/ironcore-dev/ironcore/blob/main/Makefile#L486-L488

The installation would be actually even easier if the CLI code would be part of the project itself as you then can ensure that you always use the correct version and also ensure that if something breaks you have an immediate prove in the test run.

**Comment by PlagueCZ** [comment]
Not arguing about making version matching easier, it would. The separation came from the fact, that `dpservice-go` is also needed to compile `metalnet` project.

**Comment by afritzler** [comment]
In you `go.mod` you just add the path `github.com/ironcore-dev/dpservice/cli` and you are done.

**Comment by PlagueCZ** [comment]
Adding a note here, since I encountered this situation when doing an update to the gRPC protocol.

If `dpservice-cli` and `dpservice-go` are separate respos, there can be no single PR to do that. First, `dpservice` needs to update `dpdk.proto`, implement the server part, then such PR needs to be merged and only after this `dpservice-cli` can be updated and merged.

This presents a problem, because `dpservice`'s test suite uses `dpservice-cli` to work. Thus there can be no tests enabled for a newly introduced feature that changes the protocol. It then requires two separate PRs on `dpservice` side (one that changes `dpdk.proto`, the other to enable tests).

This two-step approach is doable, because we still have a C gRPC client, so tests can at least be run manually by the developer and reviewer, but it's not automatic.

Of course all the negatives mentioned by Guvenc may still outweigh this single benefit.

**Comment by guvenc** [comment]
#552

**Comment by PlagueCZ** [comment]
Repositories `dpservice-cli`, `dpservice-go` and `dpdk-prometheus-exporter` now moved to `dpservice`.

**Comment by guvenc** [comment]
As mentioned by @PlagueCZ, this issue can be closed now.
